### ISSUE TITLE
example-dapp: update per token interface changes

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-example-dapp#103]
## What ?

Update example dapp to use the updated token interface.

## Epic

https://github.com/stellar/soroban-tools/issues/519

**Comment by 2opremio** [comment]
This ticket requires updating https://github.com/stellar/soroban-example-dapp/blob/main/contracts/crowdfund/src/lib.rs with the new token spec (and updating the corresponding function calls to their new names)

**Comment by 2opremio** [comment]
And it _may_ also:

1. require bumping the Rust SDK to an unreleased version (with the new token contract changes and a new `soroban_sdk::contractimport`)
2. bump core/QuickStart to a newer version supporting the new token interface

For all the above, we can use https://github.com/stellar/soroban-tools/pull/611 as a reference

**Comment by sreuland** [comment]
closing as done, updates were merged in #105
