### ISSUE TITLE
Server Error Error: Unsupported address type

### ISSUE THREAD

**Issue by GHesericsu** [stellar/soroban-example-dapp#110]
### What version are you using?

"version": "0.1.0",

### What did you do?

I ran `npm run dev` after I got the backend running locally. 

### What did you expect to see?
I can spin out the frontend at localhost and see the UI. 

### What did you see instead?
![Screen Shot 2023-05-17 at 6 27 00 PM](https://github.com/stellar/soroban-example-dapp/assets/60202455/c119ed59-f6e9-45a3-9e37-af5de993189b)
![Screen Shot 2023-05-17 at 6 27 17 PM](https://github.com/stellar/soroban-example-dapp/assets/60202455/45e12f90-3cf8-4380-a1a9-dcf71c1152f3)

The UI was able to run if I delete this variable `SorobanClient.Address.contract(Buffer.from(Constants.CrowdfundId, 'hex')).toScVal()` 

The issue and error looks like it's coming out from `stellar-base/lib/address.js` file

**Comment by esteblock** [comment]
Hello. This is strange.
Can you check that you have `Constants.CrowdfundId`?
Did you run the `initialize.sh` script?

**Comment by esteblock** [comment]
What do you have when you run in your console:
```
cat .soroban/crowdfund_id
```

**Comment by GHesericsu** [comment]
It all works now. Looks like `initialize.sh` failed on me last time that's all. Thank you!
