### ISSUE TITLE
Provide initialize.sh option to a remote rpc

### ISSUE THREAD

**Issue by sreuland** [stellar/soroban-example-dapp#113]
### What problem does your feature solve?
`./initialize.sh futurenet` defaults to rpc on localhost url
 
### What would you like to see?
`./initialize.sh futurenet <optional_rpc_url>` 

such as

`./initialize.sh futurenet https://rpc-futurenet.stellar.org:443`  

### What alternatives are there?
do the same commands as initialize.sh and save results manually in local `.soroban-example-dapp`

**Comment by chadoh** [comment]
Would it be worth having `./initialize.sh futurenet` use remote RPC URL by default, with fallback option for localhost? Or maybe even _always_ use remote?

**Comment by sreuland** [comment]
that default sounds more idiomatic for `futurenet` reference, and can still retain ability to override that with a custom url seems flexible enough, unless anyone has objections?

**Comment by chadoh** [comment]
implementing it now; PR soon
