### ISSUE TITLE
example-dapp: Authorize the token.approve contract call

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-example-dapp#13]
The token.approve contract call (See: https://github.com/stellar/soroban-example-dapp/blob/23640dc76ef285983a6ed0a2e452ab85dabdc8a6/pages/index.tsx#L373-L374), needs to actually get the transaction signed correctly by Freighter, otherwise the approval call will not work.

cc @sisuresh @piyalbasu

**Comment by esteblock** [comment]
This issue should be marked as closed @paulbellamy
