### ISSUE TITLE
Update for Protocol 21 and latest CLI+stellar-sdk versions

### ISSUE THREAD

**Issue by chadoh** [stellar/soroban-example-dapp#150]
### What problem does your feature solve?

This repository is v old

### What would you like to see?

it be up-to-date with latest protocol & library versions

### What alternatives are there?

Archive the repository, since [the Getting Started guide](https://developers.stellar.org/docs/smart-contracts/getting-started/create-an-app) now has people use https://github.com/stellar/soroban-astro-template with `soroban contract init --frontend-template`. That repository is probably more useful to focus on, and can more-or-less fulfill the purpose that this one was originally created for.

**Comment by pselle** [comment]
Going to start working on this!

**Comment by Julian-dev28** [comment]
> Going to start working on this!

hey @pselle how is this coming along?

**Comment by pselle** [comment]
@Julian-dev28 This was (perhaps unsurprisingly) a bit of bear, but now it's in somewhat a working state. Ideally PR soon? Working with @chadoh as well on this

**Comment by janewang** [comment]
@Shaptic Please review
