### ISSUE TITLE
LambdaHackWeek: Add Multi-Language Support

### ISSUE THREAD

**Issue by Julian-dev28** [stellar/soroban-example-dapp#156]
### **Please add PRs to the [update-P21 branch](https://github.com/stellar/soroban-example-dapp/tree/update-P21)**

**Description:**
Implement support for multiple languages in the Soroban Example DApp to enhance accessibility for users from different linguistic backgrounds.

**Tasks:**
1. **Identify Key Areas for Translation:**
   - Review the Dapp to identify all user-facing text.
   - Create a list of strings that need translation.

2. **Choose a Library for Language Support:**
   - Research and select a library (e.g., i18next, react-intl) for implementing multi-language support.
   - Integrate the chosen library into the project.

3. **Add Translations for at Least Two Languages:**
   - Create translation files for the selected languages (e.g., English and Spanish).
   - Populate the files with the translated strings.
   - Ensure context-appropriate translations.

4. **Implement Language Switcher:**
   - Add a language switcher component to the UI.
   - Ensure that the switcher updates the displayed language in real-time.

5. **Test Multi-Language Support:**
   - Test the Dapp with different language settings.
   - Ensure that all text is properly translated and displayed.
   - Verify that switching languages does not break the UI.

**Expected Outcome:**
- The Soroban Example Dapp supports multiple languages.
- Users can switch between languages seamlessly using a language switcher.
- Comprehensive and context-appropriate translations for at least two languages are available.

**Why This Is Important:**
Adding multi-language support will make the Soroban Example Dapp accessible to a broader audience, enhancing user experience and inclusivity.

**Comment by kamalbuilds** [comment]
Hey @Julian-dev28 , do we have any preferences for the library , I have seen i18next being used at a number of places  ?

Thought to ask if we have any preferences over the lib or not.

**Comment by Julian-dev28** [comment]
fixed by #167
