### ISSUE TITLE
example-dapp: Show the new contract data after the txn submission

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-example-dapp#4]
Once you submit the txn we should update the page with the new state.

Update:
- total donations
- your contributions
- crowdfund status

**Comment by paulbellamy** [comment]
The easiest solution here is probably just to trigger a re-fetch when `useSendTransaction`'s callback is successful.

**Comment by esteblock** [comment]
This was solved in https://github.com/stellar/soroban-example-dapp/commit/82adf511ec76a0dc14f35a019ff135bc74801303

At the end of the transaction, by calling sorobanContext.connect(), it update the context, and hence, updates all the values that depend on that context.

See: https://github.com/stellar/soroban-example-dapp/blob/9697fcab04f2ba399333ad33d3699f99cd4df452/components/molecules/form-pledge/index.tsx#L323

**Comment by esteblock** [comment]
Should be marked as Soved @paulbellamy
