### ISSUE TITLE
Use @soroban-react library

### ISSUE THREAD

**Issue by esteblock** [stellar/soroban-example-dapp#65]
I created the [@soroban-react](https://github.com/esteblock/soroban-react) library based on this project's code, some commits  https://github.com/stellar/soroban-example-dapp/pull/64 and insipred in the [web3-react](https://github.com/Uniswap/web3-react) library

Will work now on implementing @soroban-react library starting from this commit: https://github.com/stellar/soroban-example-dapp/commit/e4fe270465674d1d2a949078751e633c68ea8fe6

**Comment by paulbellamy** [comment]
Closed in https://github.com/stellar/soroban-example-dapp/pull/66
