### ISSUE TITLE
Update dApp tests to support the single-asset balance model.

### ISSUE THREAD

**Issue by Shaptic** [stellar/soroban-example-dapp#81]
After #80, the tests still need to be updated.

Based on Discord threads ([1](https://discord.com/channels/897514728459468821/1062064952086626374) and [2](https://discord.com/channels/897514728459468821/1062093754011504660)), we need to manually create a `LedgerSnapshot` instance containing the `xdr::TrustLineEntry`s to the token admin for each of the participating accounts.

The following code gets part of the way there, but it relies on importing `stellar_xdr` as a separate crate, which conflicts with `stellar_sdk::xdr`, meaning the trustline entries can't actually be added to the `entries` vector due to differing types:

<details>

```rust
        // where `fxdr` comes from:
        //
        //    extern crate xdr as full_xdr;
        //    use full_xdr::next as fxdr;

        let token_admin = e.accounts().generate_and_create();

        let snap = e.to_snapshot();
        let entries = &snap.ledger_entries;

        for trustor in &std::vec![recipient, user1, user2] {
            let token_issuer = fxdr::AccountId(
                match TryInto::<xdr::AccountId>::try_into(token_admin).unwrap().0 {
                    xdr::PublicKey::PublicKeyTypeEd25519(pk) => {
                        fxdr::PublicKey::PublicKeyTypeEd25519(fxdr::Uint256(pk.0))
                    }
                },
            );

            let account_id = match TryInto::<xdr::AccountId>::try_into(trustor).unwrap().0 {
                xdr::PublicKey::PublicKeyTypeEd25519(pk) => {
                    fxdr::PublicKey::PublicKeyTypeEd25519(fxdr::Uint256(pk.0))
                }
            };

            let asset = fxdr::TrustLineAsset::CreditAlphanum4(fxdr::AlphaNum4 {
                asset_code: fxdr::AssetCode4([0x41; 4]),
                issuer: token_issuer,
            });

            let trustline = fxdr::LedgerKey::Trustline(fxdr::LedgerKeyTrustLine {
                account_id: fxdr::AccountId(account_id),
                asset,
            });

            let trustline_entry = (Box::new(key), Box::new(trustline));
            entries.push(trustline_entry);
        }

        snap.update_entries(&entries);
        e = soroban_sdk::Env::from_snapshot(snap);
```

</details>

Once `stellar_sdk` exposes all XDR types (or provides a convenient way to make trustlines), this can be modified to work.

**Comment by paulbellamy** [comment]
Once fixed, we need to revert commit https://github.com/stellar/soroban-example-dapp/pull/80/commits/56f5bef33da7cda9020b04ceef8877ed17c1ad3e

**Comment by esteblock** [comment]
This issue should be marked as Closed @paulbellamy
