### ISSUE TITLE
Publish a docker image when we do a release of this repo

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-example-dapp#97]
### What problem does your feature solve?

Right now, users have to build their own `soroban-preview` docker image to run stuff locally.

### What would you like to see?

We should add a github action which triggers when there is a release, and builds/pushes the docker image to dockerhub.

### What alternatives are there?

Spawned from: https://github.com/stellar/soroban-example-dapp/pull/94

**Comment by esteblock** [comment]
Hello. Just to add some info about the alternative:

I was supporting the following repo: https://github.com/esteblock/soroban-preview-docker/
Docker images then published in https://hub.docker.com/repository/docker/esteblock/soroban-preview/general

In the repo each folder will hold a different Preview Dockerfile.
We could also add a github action to publish them

**Comment by mollykarcher** [comment]
We can use quickstart as a model for how to set this up, but multi-arch will add a lot of complexity here

**Comment by esteblock** [comment]
> We can use quickstart as a model for how to set this up, but multi-arch will add a lot of complexity here

You mean that we can also install soroban-cli in quickstart, and then execute soroban-cli commands inside the quickstart containter? That would be great! Just use one container for all!
